### ISSUE TITLE
CI is not working

### ISSUE THREAD

**Issue by unaizorrilla** [rynowak/opulence#4]
Hi @rynowak 

CI.yml is not working, probably is related with https://github.com/NuGet/Home/issues/8580 , I try to workaround with the information on the issue but dotnet nuget push on linux is not working well with github actions.

**Comment by rynowak** [comment]
Yeah :(

**Comment by rynowak** [comment]
I might switch this to a public feed anyway because I want other people to be able to try.

**Comment by unaizorrilla** [comment]
I'm trying to solve on Esquio using 

https://github.com/Xabaril/Esquio/blob/master/.github/workflows/nightly.yml

```
- name: Publish nuget
      run: |
          for f in ./artifacts/*.nupkg
          do
            curl -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
          done
      shell: bash
```

**Comment by rynowak** [comment]
Yeah I had this working, and it suddenly stopped. let me know if you get something working.

**Comment by unaizorrilla** [comment]
It is a issue on ubuntu-latest, on windows-latest working fine. In my case i solve the problem using curl directly to push packages.

https://github.com/Xabaril/Esquio/blob/master/.github/workflows/nightly.yml

**Comment by rynowak** [comment]
I'll try swapping back to curl then, I don't need windows 😆

**Comment by rynowak** [comment]
@unaizorrilla are you sure yours is working?

```txt
< HTTP/1.1 409 Conflict
< Content-Security-Policy: default-src 'none';
< Content-Type: application/json; charset=utf-8
< Server: GitHub Registry
< Strict-Transport-Security: max-age=31536000;
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Nuget-Warning: Error: Version Esquio of "2.0.1-nightly" has already been pushed.
< X-Xss-Protection: 1; mode=block
< Date: Tue, 07 Jan 2020 06:03:31 GMT
< Content-Length: 104
< X-GitHub-Request-Id: 0500:022F:960A:71548:5E141F33
* HTTP error before end of send, stop sending
```

https://github.com/Xabaril/Esquio/commit/7894a7f0b7df18e947d8558e505a4667c497ced8/checks?check_suite_id=387435793

**Comment by rynowak** [comment]
Fixed mine! Thanks for the pointer.

btw `curl --silent --show-error --fail` supposedly will return non-zero exit code on failure.

**Comment by Nixill** [comment]
This took me way too much digging to find, but you know what, it *worked*. **Thank you** @unaizorrilla.
